server:
  port: 9090

spring:
  application:
    name: api-gateway
  server:
   servlet:
    context-path: /api

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/