server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/shabarish
    username: root
    password: Shabarish@8945
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # ✅ Correct Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        shutdown-timeout: 100ms  # optional, graceful shutdown

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ✅ 🔥 Tracing Configuration
management:
  tracing:
    sampling:
      probability: 1.0  # capture all traces (dev only)

  otel:
    service-name: Auth-service
    exporter:
      otlp:
        endpoint: http://localhost:4317
        protocol: grpc  # required for Jaeger OTLP

  endpoints:
    web:
      exposure:
        include: "*"

# ✅ Rate Limiter Properties
rate-limiter:
  prefix: "rate_limit:"               # Redis key prefix
  global:
    window-seconds: 60                # 60 seconds window
    max-requests: 500                 # 500 requests per user globally
  service:
    window-seconds: 60                # 60 seconds window
    max-requests: 100                 # 100 requests per user for Auth service