server:
  port: 8080

spring:
  application:
    name: member-service

  mongodb:
    uri: mongodb://localhost:27017/ETL

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      serviceFourCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - java.net.ConnectException
          - java.net.UnknownHostException
          - feign.RetryableException

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.cloud.openfeign: DEBUG