server:
  port: 8081

spring:
  application:
    name: service-for-client
  datasource:
    url: jdbc:mysql://localhost:3306/shabarish
    username: root
    password: Shabarish@8945
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/